services:
  - type: web
    name: joanis-portfolio
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /blog/*
        destination: /index.html
      - type: rewrite
        source: /blog
        destination: /index.html

